### ISSUE TITLE
Add auto paste functionality too?

### ISSUE THREAD

**Issue by rohit-gohri** [jchook/emoji-menu#1]
This is a cool utility, would be even better if it had an option to paste the emoji too.

Could use xdotool maybe. I'm trying to get it to work, will comment if it works out

**Comment by rohit-gohri** [comment]
This worked out in the end for xbindkeys: 

```
"emoji-menu && sleep 0.1 && xdotool key --window $(xdotool getactivewindow) --clearmodifiers ctrl+v"
  control+alt + x

```

Not sure if sleep is needed, I added it just to let the window focus

**Comment by jchook** [comment]
Hey thanks! 

The script [does use](https://github.com/jchook/emoji-menu/blob/ff879f13d4eb7a3abf26405b64ede1c1ea0a9ce7/bin/emoji-menu#L40) `xdotool` when given the `-t` flag :)

`emoji-menu -t`

For some reason it doesn't work in certain cases, e.g. in [Telegram for Desktop](https://desktop.telegram.org/). I'm interested in trying out your additional xdotool magic there.

**Comment by rohit-gohri** [comment]
I have telegram, I'll try it

**Comment by rohit-gohri** [comment]
> The script [does use](https://github.com/jchook/emoji-menu/blob/ff879f13d4eb7a3abf26405b64ede1c1ea0a9ce7/bin/emoji-menu#L40) `xdotool` when given the `-t` flag :)
> 
> `emoji-menu -t`
> 

🙈 I didn't see that. Should have read the docs first. 
~I think just using the getactivewindow part might fix the existing script.~ Tried it, with telegram it only works with pasting. Good enough workaround.

Tested my key combo in telegram, it works 😀

**Comment by jchook** [comment]
> Tested my key combo in telegram, it works 😀

Right on. Thanks for looking into this.

Now that you mention it, I think I did go down the ctrl-v path before, but didn't love the solution since some applications (like terminal emulators) do not use ctrl-v for paste (often ctrl-shift-v).

Then I wrote a (partially-done) solution for [typing unicode into Linux applications](https://en.wikipedia.org/wiki/Unicode_input#In_X11_(Linux_and_other_Unix_variants_including_Chrome_OS)) using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>u</kbd>. Surprisingly, the OS does not provide this functionality, and so it doesn't work in certain applications such as [alacritty](https://github.com/alacritty/alacritty/issues/866). Meanwhile, `xdotool type 🥑` _does_ work in those applications and feels more correct.

Telegram seems like the only app where it fails, so perhaps I can settle with opening an issue there.

Conceptually, it seems like a good idea to keep "copy selection to clipboard" separate from "type selection" so that choosing an emoji doesn't hijack your clipboard unnecessarily. Perhaps we have a 3rd option for "copy selection to clipboard and paste it automatically", or simply document the issue and give xbindkeys config examples in the README.

**Comment by rohit-gohri** [comment]
I thought about the terminal option too but I don't think I'll be using emojis there anytime soon so I was okay with ctrl+v. 

I guess best way would be to mention the issue with Telegram and it's solution, and let the user choose. Also since Telegram has their own emoji picker "-t" option is sufficient for most use cases. 

Feel free to close the issue. 

PS : I'm getting some good use out of this, this is pretty cool 😎

**Comment by jchook** [comment]
> PS : I'm getting some good use out of this, this is pretty cool 😎

Very pleased that you find it useful!
